export const imageBank = {
  MyxelliaIcon: "../../assets/Myxellia-admin-Icon.svg",
  BellNotificationIcon: "../../assets/Bell-Notification-Icon.svg",
  BudgetingIcon: "../../assets/Budgeting.svg",
  CalenderIcon: "../../assets/Calendar.svg",
  MessageNotificationIcon: "../../assets/message-notif.svg",
  HomeDashboardIcon: "../../assets/Home-Dashboard-Icon.svg",
  ListingsIcon: "../../assets/Toolbox-Listings-Icon.svg",
  UsersIcon: "../../assets/User-Profile-Icon.svg",
  RequestIcon: "../../assets/Request-Icon.svg",
  ApplicationsIcon: "../../assets/Applications-Icon.svg",
  ListingsOverviewIcon: "../../assets/Listings-Overview-Icon.svg",
  UsersOverviewIcon: "../../assets/Users-Overview.svg",
  GreenArrowUp: "../../assets/GreenArrowUp.svg",
  DeepGreenArrowDown: "../../assets/DeepGreenArrowDown.svg",
  RedArrowDown: "../../assets/RedArrowDown.svg",
  ArrowRight: "../../assets/arrow-right.svg",
  ArrowLeft: "../../assets/arrow-left.svg",
  BudgetModalOverlay: "../../assets/BudgetModalOverlay.svg",
  Calculator: "../../assets/calculator.svg",
  BudgetTracker: "../../assets/BudgetTracker.svg",
  AccountCategory: "../../assets/AccountCategory.svg",
  Analytics: "../../assets/Analytics.svg",
  MostClickedUrbanPlaza: "../../assets/MostClickedUrbanPlaza.svg",
  MostWatchedlistedUrbanPlaza: "../../assets/MostWatchedlistedUrbanPlaza.svg",
  HottestListingUrbanPlaza: "../../assets/HottestListingUrbanPlaza.svg",
};
